package org.example;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class CreateUserTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "E:\\webdriver\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void createUserTest() throws InterruptedException {
        driver.get("https://diary.ru/");
        driver.findElement(By.linkText("Регистрация")).click();
        driver.findElement(By.id("signupform-username")).click();
        driver.findElement(By.id("signupform-username")).sendKeys("TestTset5");
        driver.findElement(By.id("wrapper")).click();
        driver.findElement(By.id("signupform-password")).click();
        driver.findElement(By.id("signupform-password")).clear();
        driver.findElement(By.id("signupform-password")).sendKeys("TestTset5");
        driver.findElement(By.id("signupform-email")).click();
        driver.findElement(By.id("signupform-email")).sendKeys("TestTset5@test.com");
        driver.findElement(By.id("chk_box_user_confirm")).click();
        driver.findElement(By.id("signup_btn")).click();
        driver.findElement(By.cssSelector(".radio:nth-child(4) input")).click();
        new WebDriverWait(driver, 10).until(ExpectedConditions.presenceOfElementLocated(By.name("new-blogs-button"))).click();
        // driver.findElement(By.name("new-blogs-button")).click();
        assertThat(new WebDriverWait(driver, 10).until(ExpectedConditions
                .presenceOfElementLocated(By.cssSelector(".block:nth-child(1) > h1"))).getText(), is("Популярное"));
        // assertThat(driver.findElement(By.cssSelector(".block:nth-child(1) > h1")).getText(), is("Популярное"));
    }
}
