package org.example;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CreateNewProjectTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "E:\\webdriver\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testCreateNewProject() {
        driver.get("https://crm.geekbrains.space/user/login");
        driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
        driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
        driver.findElement(By.id("_submit")).click();
        {
            WebElement element = driver.findElement(By.linkText("Проекты"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.xpath("//div[@id=\"main-menu\"]/ul/li[3]/a"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.linkText("Мои проекты")).click();
        driver.findElement(By.linkText("Создать проект")).click();
        driver.findElement(By.name("crm_project[name]")).sendKeys("TestName33");
        {
            WebElement element = driver.findElement(By.cssSelector(".select2-default > .select2-chosen"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.id("select2-drop-mask"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector(".lang-ru")).click();
        driver.findElement(By.xpath("//*[@id=\"select2-drop\"]/div/input")).sendKeys("123");
        driver.findElement(By.cssSelector(".select2-result-label")).click();
        {
            WebElement dropdown = driver.findElement(By.name("crm_project[businessUnit]"));
            dropdown.findElement(By.cssSelector("*[value='1']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.name("crm_project[curator]"));
            dropdown.findElement(By.cssSelector("*[value='5']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.name("crm_project[rp]"));
            dropdown.findElement(By.cssSelector("*[value='65']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.name("crm_project[administrator]"));
            dropdown.findElement(By.cssSelector("*[value='11']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.name("crm_project[manager]"));
            dropdown.findElement(By.cssSelector("*[value='20']")).click();
        }
        driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
        assertThat(driver.findElement(By.cssSelector(".oro-subtitle")).getText(), is("Все Проекты"));
    }
}
